## Manejo vectores y matrices en NumPy

NumPy es un paquete que proporciona herramientas y técnicas para manipular estructuras de datos con vectores y matrices. Posee una amplia colección de herramientas y técnicas que se pueden utilizar para resolver problemas mátematicos.

A continuación encontrá algunas funciones muy útiles tales como:
- Creación de matrices
- Suma y resta de vectores
- Producto de dos vectores
- Producto de dos matrices
- Multiplicación matricial
- Indexación de matrices


In [1]:
import numpy as np

### Creación de matrices, info y operaciones

In [2]:
#Creacion de array de ceros y unos
zeros=np.zeros(10)
print("Array de 10 ceros:", zeros)

ones=np.ones(10)
print("Array de 10 unos:", ones)

array1 = np.arange(5)  # Array de 5 enteros contando el 0
print("Array de 5 enteros: ",array1)

line = np.linspace(0.0, 1.0, 5) #start, stop, num de puntos
print("Array organizados unif.: ",line)

v1 = np.array([8,6,-5,76,9.7]) #Array de una lista
print("Array de una lista: ",v1)

Array de 10 ceros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array de 10 unos: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array de 5 enteros:  [0 1 2 3 4]
Array organizados unif.:  [0.   0.25 0.5  0.75 1.  ]
Array de una lista:  [ 8.   6.  -5.  76.   9.7]


In [29]:
a = [1,2,3]
b = [1,5,6]
a + b

[1, 2, 3, 1, 5, 6]

In [30]:
v1 = np.array([1,2,3])
v2 = np.array([1,5,6])
v1 + v2

array([2, 7, 9])

In [31]:
v1 == v2

array([ True, False, False])

In [32]:
# producto elemento a elemento
prod1 = v1*v2
print ("Producto elemeto a elemento",prod1)

#Producto matricial
prod1 = np.dot(v1,v2)
print ("Producto matricial",prod1)

Producto elemeto a elemento [ 1 10 18]
Producto matricial 29


In [14]:
a = np.random.random(size=(3,5))
a

array([[0.34762853, 0.29646372, 0.17969517, 0.67191749, 0.47067794],
       [0.42689303, 0.70236123, 0.28669742, 0.77777008, 0.81390791],
       [0.30663262, 0.4286246 , 0.15508931, 0.84464978, 0.71484773]])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.arange(-3,20)

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,
       14, 15, 16, 17, 18, 19])

In [121]:
np.array([[1,2],[2,1],[3,1]])

array([[1, 2],
       [2, 1],
       [3, 1]])

In [19]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [38]:
a = np.random.randint(100, size=(3,4))
a

array([[24, 73, 99, 70],
       [91, 58, 17, 84],
       [81, 14, 34, 51]])

In [39]:
a.shape

(3, 4)

In [40]:
a.size

12

In [41]:
a.T

array([[24, 91, 81],
       [73, 58, 14],
       [99, 17, 34],
       [70, 84, 51]])

In [25]:
a.dtype

dtype('int32')

In [42]:
b = a.astype(np.float32)
b

array([[24., 73., 99., 70.],
       [91., 58., 17., 84.],
       [81., 14., 34., 51.]], dtype=float32)

In [27]:
b.dtype

dtype('float32')

In [34]:
a = np.array([3,5,4])
a

array([3, 5, 4])

In [35]:
a.sum()

12

In [36]:
np.sum(a), np.max(a), np.min(a), np.mean(a), np.std(a), np.product(a)

(12, 5, 3, 4.0, 0.816496580927726, 60)

_Reshape_: Asigna una nueva forma a la matriz ya sea un entero para una dimensión o una tupla para N-Dimensiones

In [44]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [43]:
a = np.arange(6).reshape((3, 2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [45]:
b = np.arange(6).reshape((3,1,2))
b

array([[[0, 1]],

       [[2, 3]],

       [[4, 5]]])

In [46]:
b = b.reshape((6))
b

array([0, 1, 2, 3, 4, 5])

¡Cuidado con la asignación de variables! Python usa variables referenciadas. Si se requiere hacer una copia se debe usar el método ".copy".

In [47]:
m1 = np.arange(10)
m1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
m2 = m1
m2[0] = 6

In [49]:
m1

array([6, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
m3 = np.copy(m1)
m3[0] = 0

In [51]:
print(m1, m3)

[6 1 2 3 4 5 6 7 8 9] [0 1 2 3 4 5 6 7 8 9]


### Indexación

Para hacer una indexación en matrices se accede con los corchetes y siempre se define así: [filas,columnas]. Observa que la separación se realiza con una coma ( , )

    x = matrix[filas, columnas]
    
Si deseo escoger entre la fila x hasta y debe ser separado por dos puntos **:**, de la siguiente forma:

    x = matrix[x:y,]
    

De la misma forma aplica para las columnas, si quiero la primera columna:

    x = matrix[0:2,0:1]
    
Acceder a los últimas posiciones:

    x = matrix[0:-1,0:-1]

In [59]:
a = np.random.randint(100, size=(8,4))
a

array([[46, 13, 19, 93],
       [81, 19, 45, 99],
       [75, 38, 66, 49],
       [26, 75,  0, 50],
       [70, 79, 36, 30],
       [ 8,  7, 58, 76],
       [ 9, 97, 70, 24],
       [74, 38, 95, 28]])

In [60]:
a[1]

array([81, 19, 45, 99])

In [61]:
a[:,1]

array([13, 19, 38, 75, 79,  7, 97, 38])

In [62]:
a[1,:]

array([81, 19, 45, 99])

In [70]:
a[:,1:3]

array([[13, 19],
       [19, 45],
       [38, 66],
       [75,  0],
       [79, 36],
       [ 7, 58],
       [97, 70],
       [38, 95]])

In [71]:
a[2:5,1:3]

array([[38, 66],
       [75,  0],
       [79, 36]])

In [75]:
a[-1,-1]

28

In [76]:
a[5:-1,-1]

array([76, 24])

### Boolean indexes

In [77]:
a = np.random.randint(100, size=(10))
a

array([26, 28, 56, 66, 70, 47, 12, 25, 56, 58])

In [78]:
a[[ True,  True, False, False, False, False,  False, False, False, True]]

array([26, 28, 58])

In [79]:
a<50

array([ True,  True, False, False, False,  True,  True,  True, False,
       False])

In [80]:
a[a<50]

array([26, 28, 47, 12, 25])

In [82]:
a[(a<50) & (a%2==0)]

array([26, 28, 12])

In [114]:
a = np.random.randint(10, size=(5)) < 5
a

array([False,  True,  True, False, False])

In [115]:
b = np.random.randint(10, size=(5)) < 5
b

array([False,  True,  True, False,  True])

In [116]:
np.logical_and(a, b)

array([False,  True,  True, False, False])

In [117]:
np.logical_or(a, b)

array([False,  True,  True, False,  True])

In [118]:
np.logical_not(a)

array([ True, False, False,  True,  True])

### Axis Operations

In [83]:
a = np.random.randint(100, size=(4,6))
a

array([[42, 56, 65, 88, 52, 19],
       [89, 83, 68, 98, 85, 17],
       [94, 38, 17, 41, 43, 48],
       [ 6, 72, 46, 73, 70, 73]])

In [84]:
np.max(a, axis=0)

array([94, 83, 68, 98, 85, 73])

In [85]:
np.max(a, axis=1)

array([88, 98, 94, 73])

In [86]:
np.mean(a, axis=1)

array([53.66666667, 73.33333333, 46.83333333, 56.66666667])

In [87]:
np.argmax(a, axis=1)

array([3, 3, 0, 3], dtype=int64)

### Concatenar vectores y matrices


In [99]:
a = np.array([[1,5,9], [2,6,10]])
b = np.array([[3,7,11], [4,8,12]])
print(a)
print()
print(b)

[[ 1  5  9]
 [ 2  6 10]]

[[ 3  7 11]
 [ 4  8 12]]


In [100]:
np.concatenate((a,b), axis=0)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [101]:
np.concatenate((a, b), axis=1)

array([[ 1,  5,  9,  3,  7, 11],
       [ 2,  6, 10,  4,  8, 12]])

In [102]:
np.ravel(a) # We can use reshape as well

array([ 1,  5,  9,  2,  6, 10])

---

### Broadcasting

It is a very useful technique for performing mathematical operations between arrays of different shapes.

![Broadcasting](images/python_broadcasting.png)

In [141]:
x = np.array([[1],[2],[3],[4]])
x

array([[1],
       [2],
       [3],
       [4]])

In [142]:
x.shape

(4, 1)

In [143]:
x + 100

array([[101],
       [102],
       [103],
       [104]])

In [144]:
x = np.array([[1, 2, 3],[4, 5, 6]])
print(x, x.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


In [145]:
y = np.array([100, 200, 300])
print(y, y.shape)

[100 200 300] (3,)


"a rank 1 array": neither a row vector nor a column vector

In [146]:
y = y.reshape((1, y.shape[0]))
print(y, y.shape)

[[100 200 300]] (1, 3)


In [147]:
x + y

array([[101, 202, 303],
       [104, 205, 306]])

In [154]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [155]:
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [156]:
np.round(3.141592, 2)

3.14

In [150]:
x*6

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54])

In [151]:
x**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [160]:
np.round(np.sin(x), 2)

array([ 0.  ,  0.84,  0.91,  0.14, -0.76, -0.96, -0.28,  0.66,  0.99,
        0.41])

### Vectorization

Whenever possible use matrix operations and avoid explicit loops. It provides computational efficiency and clarity.

In [182]:
a = np.random.randint(100, size=(6,10))
a

array([[32, 78, 21, 95, 67, 84, 89, 45, 90, 90],
       [83, 27, 25, 31, 27, 85, 16, 46, 76, 31],
       [18,  8, 34, 90, 73, 47, 55, 46, 71, 42],
       [37, 72, 99, 17, 46, 98, 79, 27, 83, 78],
       [42, 11, 67, 26, 41, 76, 30, 24,  8, 12],
       [40,  4, 27, 73, 16, 77, 73, 22, 98, 12]])

In [183]:
a.shape

(6, 10)

In [184]:
values = []
for row in range(a.shape[0]):
    total_row = 0
    for column in range(a.shape[1]):
        total_row += a[row][column]
    values.append(total_row / a.shape[1])
np.array(values)

array([69.1, 44.7, 48.4, 63.6, 33.7, 44.2])

In [185]:
np.mean(a, axis=1)

array([69.1, 44.7, 48.4, 63.6, 33.7, 44.2])

In [186]:
%timeit -n 10000 -r 5 np.mean(a, axis=1)

16.2 µs ± 2.2 µs per loop (mean ± std. dev. of 5 runs, 10000 loops each)


In [187]:
%timeit -n 10000 -r 5 np.array([np.mean(a[i,:]) for i in range(a.shape[0])])

96.9 µs ± 5.95 µs per loop (mean ± std. dev. of 5 runs, 10000 loops each)


In [201]:
a = np.random.randint(100, size=(10000,100))
b = np.random.randint(200, size=(10000,1))
print(a.shape, b.shape)

(10000, 100) (10000, 1)


The mean of the elements of `a` that are greater to its corresponding position in `b`.

In [202]:
np.mean(a[a>b])

66.59197266518562

Notice! We also used broadcasting because a and b have different dimenssions!